name: Build AppImage

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AppImage tools
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2
          wget -q https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Create AppImage structure
        run: |
          mkdir -p appdir/usr/{bin,lib,share/applications,share/icons/hicolor/256x256/apps}
          cp $(which python3.8) appdir/usr/bin/
          python3 -m pip install --target=appdir/usr/lib/python3.8/site-packages -r requirements.txt
          cp src/hello.py appdir/usr/bin/
          cp appimage/AppRun appdir/
          chmod +x appdir/AppRun

      - name: Create desktop entry
        run: |
          echo "[Desktop Entry]
          Name=Flask Hello World
          Exec=AppRun
          Icon=flask-hello
          Type=Application
          Categories=Development;" > appdir/flask-hello.desktop

      - name: Build AppImage
        run: |
          ./appimagetool-x86_64.AppImage appdir flask-hello.AppImage

      - name: Upload AppImage
        uses: actions/upload-artifact@v4
        with:
          name: flask-hello-appimage
          path: flask-hello.AppImage